### ISSUE TITLE
Extract action space info

### ISSUE THREAD

**Issue by alfaevc** [deepmind/rgb_stacking#2]
Hi, my peers and I are really confused about extracting the action space information from the environment i.e. env = environment.rgb_stacking(observation_set=environment.ObservationSet.VISION_ONLY, object_triplet='rgb_test_triplet1'). Can you provide any guidance on that? env.action_space is not the right way to do it obviously.

**Comment by alaurens** [comment]
Hello, 

The command you are looking for is `env.action_spec`. That will return the spec of the action that the environment expects to receive. I hope this answers your question.
