### ISSUE TITLE
MPO implementation missing

### ISSUE THREAD

**Issue by alfaevc** [deepmind/rgb_stacking#3]
Hi, are you guys planning to upload how you implement MPO in this task to the repo?

**Comment by alaurens** [comment]
Hello,

We will not be uploading any implementations of the agent, if you are interested in deepmind implementation of agents please visit https://github.com/deepmind/acme/ and for the agent implementation of MPO please see https://github.com/deepmind/acme/tree/master/acme/agents/tf/mpo.
